### ISSUE TITLE
Exit code -11 during "megahit --test" [OSX]

### ISSUE THREAD

**Issue by apcamargo** [voutcn/megahit#223] opened 2019-07-10 00:21 UTC
I'm updating MEGAHIT's Bioconda recipe to make it ready for the new release. However, the test is failing for the OSX build.

```
16:53:47 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:47 2019] k list: 21,29,39,59,79,99,119,141
16:53:47 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:47 2019] Extracting solid (k+1)-mers for k = 21
16:53:47 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:47 2019] Building graph for k = 21
16:53:48 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:48 2019] Assembling contigs from SdBG for k = 21
16:53:48 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:48 2019] Local assembling k = 21
16:53:48 BIOCONDA INFO (ERR) --- [Tue Jul  9 16:53:48 2019] Extracting iterative edges from k = 21 to 29
16:53:48 BIOCONDA INFO (ERR) Error occurs when running iterator for k = 21 to k = 29, please refer to /tmp/megahit_test_luy87mn7/out/log for detail
16:53:48 BIOCONDA INFO (ERR) [Exit code -11]
```

[Pull request in `bioconda-recipes`](https://github.com/bioconda/bioconda-recipes/pull/16207)
[Failed build](https://circleci.com/gh/bioconda/bioconda-recipes/64145)

**Comment by voutcn** [comment] 2019-07-14 06:17
Please try https://github.com/voutcn/megahit/releases/tag/v1.2.6
I've tested it on my macbook.
Thank you for updating Megahit on bio-conda!

**Comment by apcamargo** [comment] 2019-07-14 15:25
Thank you @voutcn !

The recipe is still failing because MEGAHIT won't detect available memory during the test of the build. Is this related to the previous bug?

`08:21:11 BIOCONDA INFO (ERR) megahit: Failed to detect available memory size, please specify memory size in byte via -m option`

[Failed build](https://circleci.com/gh/bioconda/bioconda-recipes/64758?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by voutcn** [comment] 2019-07-14 20:19
It seems that bio-conda's ci is running on a rather old MacOS 
@apcamargo Could you try https://github.com/voutcn/megahit/releases/tag/v1.2.6.1?

**Comment by voutcn** [comment] 2019-07-14 22:57
@apcamargo I saw that it is still failing. Unfortunately my Macbook is down and I cannot test on MacOS right now. I will leave this issue open and try to fix it ASAP.

**Comment by voutcn** [comment] 2019-07-14 23:01
An alternative solution is to change the test commands to
```
megahit --test -m 5e6
megahit --test -m 5e6 --kmin-1pass
```

**Comment by apcamargo** [comment] 2019-07-15 18:51
Thank you again @voutcn 

Do you think this is a good solution? Wouldn't macOS users get a buggy build? If you think this isn't a big problem, I can do that!

**Comment by voutcn** [comment] 2019-07-16 03:17
@apcamargo I think it is good. This is not a bug. Memory size detection is just a feature for most Unix-like operating systems.

According to [this issue](https://github.com/voutcn/megahit/issues/191#issuecomment-511101991), only outdated Mac OS' are affected. Users can still run Megahit by manually setting the `-m` parameter.

**Comment by apcamargo** [comment] 2019-07-16 23:58
The build was successful now. Thank you @voutcn !

**Comment by voutcn** [comment] 2019-07-17 03:58
Thank you @apcamargo ! Closing this issue.

**Closed by voutcn** 2019-07-17 03:58 UTC

**Comment by mw55309** [comment] 2021-05-10 11:09
I can confirm that this bug also occurs on Google Cloud - their standard VM OS obviously doesn;t have installed whatever library you are using
