### ISSUE TITLE
Help with [Exit code -11]

### ISSUE THREAD

**Issue by jmm1005** [voutcn/megahit#88] opened 2016-05-27 20:01 UTC
Hi, I am running Megahit v1.0.5 and get this error during the assembly step:

```
[assembler.cpp             : 179]     Tips removal done! Time elapsed(sec): 553.287005
[assembler.cpp             : 188]     unitig graph size: 15292812, time for building: 1147.039690
```

Error occurs when assembling contigs for k = 21, please refer to Assembly/S032_final.log for detail
[Exit code -11]

It is similar to the problem listed in the Wiki, but not the same exit code. 

Can you help me figure out what is causing this?
[S032_final.log.txt](https://github.com/voutcn/megahit/files/287270/S032_final.log.txt)

**Comment by voutcn** [comment] 2016-05-29 06:07
It will take me some time to figure it out.
Before I push a patch, how about rerunning it with `--continue` option and see if the program crashes at the same place?

**Comment by jmm1005** [comment] 2016-05-31 13:43
Tried rerunning it with --continue and it crashed in exactly the same place and gave the same error and exit code.

**Comment by voutcn** [comment] 2016-06-03 09:29
Hmm, very strange. Is it possible to let me play with your data?

**Comment by jmm1005** [comment] 2016-06-03 11:37
Sure, if you think it will help. I can also put you in contact with our HPC team who did some troubleshooting with the data on our system before I opened this issue if that well help.

**Comment by voutcn** [comment] 2016-06-03 14:29
Great, it is much easier if I can reproduce the fault with your data. Please contact me by voutcn at gmail dot com.
If your HPC team encountered any problem with MEGAHIT, I'd like to take a look, too.

**Comment by alex-b-chase** [comment] 2017-03-22 14:26
Has this been resolved? I am running megahit on our HPC and have the same exit code -11.

> --- [Tue Mar 21 20:20:23 2017] Assembling contigs from SdBG for k = 31 ---
> cmd: /data/apps/megahit/megahit_asm_core assemble -s megahit/tmp/k31/31 -o megahit/intermediate_contigs/k31 -t 48 --min_standalone 1000 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
>     [assembler.cpp             : 148]     Loading succinct de Bruijn graph: megahit/tmp/k31/31
> Error occurs when assembling contigs for k = 31, please refer to megahit/log for detail
> [Exit code -11]
[log.txt](https://github.com/voutcn/megahit/files/861703/log.txt)
I am running 46 paired-end libraries from soil and have not managed to get past this first step. On my local machine, I run out of memory, so the HPC is the only way I can assemble this data. Here are the parameters I am using:

> megahit \
> -1 $READ1 \
> -2 $READ2 \
> -t 48 \
> --min-count 3 \
> --k-list 31,41,51,61,71,81,91,95,101,105,111 \
> --kmin-1pass \
> --min-contig-len 1000 \
> --memory 0.95 \
> --out-dir $FILENAME \
> --continue

**Comment by voutcn** [comment] 2017-04-15 02:09
@alex-b-chase Just guessing, you are running out of disk space.

By checking my emails I found that I cannot reproduce jmm1005's error even with his data. But we do not talk about this issue anymore. I am closing this issue.

Should you have more questions please open a new issue.

**Closed by voutcn** 2017-04-15 02:09 UTC
